#pragma once

enum class LogsCode
{
    SUCCESS,

    DATABASE_NOT_SELECTED,
    TABLE_NOT_SELECTED,

    DATABASE_NOT_FOUND,
    TABLE_NOT_FOUND,

    DATABASE_ALREADY_EXISTS,
    TABLE_ALREADY_EXISTS,

    COLUMN_ALREADY_EXISTS,
    COLUMN_NOT_FOUND,
    
    PRIMARY_KEY_VIOLATION,
    FOREIGN_KEY_VIOLATION,
    NOT_NULL_VIOLATION,
    UNIQUE_VIOLATION,

    FILE_ERROR,
    INVALID_COMMAND
};
